config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  resources :tadpoles

  resource :tadpoles do
    get ":id/evolve", :to => "tadpoles#evolve", :as => "evolve"
  end

  resources :frogs do
    resources :tadpoles
  end

  resources :ponds

end

app/models/frog.rb
class Frog < ActiveRecord::Base
  has_many :tadpoles
  belongs_to :pond
end

app/models/pond.rb
class Pond < ActiveRecord::Base
  has_many :frogs
  has_many :tadpoles, through: :frogs
end

app/models/tadpole.rb
class Tadpole < ActiveRecord::Base
  belongs_to :frog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frogs_controller.rb
class FrogsController < ApplicationController
  before_action :set_frog, only: [:show, :edit, :update, :destroy]

  # GET /frogs
  # GET /frogs.json
  def index
    @frogs = Frog.all
  end

  # GET /frogs/1
  # GET /frogs/1.json
  def show
  end

  # GET /frogs/new
  def new
    @frog = Frog.new
  end

  # GET /frogs/1/edit
  def edit
  end

  # POST /frogs
  # POST /frogs.json
  def create
    @frog = Frog.new(frog_params)
    respond_to do |format|
      if @frog.save
        format.html { redirect_to @frog, notice: 'Frog was successfully created.' }
        format.json { render :show, status: :created, location: @frog }
      else
        format.html { render :new }
        format.json { render json: @frog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frogs/1
  # PATCH/PUT /frogs/1.json
  def update
    respond_to do |format|
      if @frog.update(frog_params)
        format.html { redirect_to @frog, notice: 'Frog was successfully updated.' }
        format.json { render :show, status: :ok, location: @frog }
      else
        format.html { render :edit }
        format.json { render json: @frog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frogs/1
  # DELETE /frogs/1.json
  def destroy
    @frog.destroy
    respond_to do |format|
      format.html { redirect_to frogs_url, notice: 'Frog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frog
      @frog = Frog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frog_params
      #params[:frog]
      params.require(:frog).permit(:name, :color, :pond_id)
    end
end

app/controllers/ponds_controller.rb
class PondsController < ApplicationController
  before_action :set_pond, only: [:show, :edit, :update, :destroy]

  # GET /ponds
  # GET /ponds.json
  def index
    @ponds = Pond.all
  end

  # GET /ponds/1
  # GET /ponds/1.json
  def show
  end

  # GET /ponds/new
  def new
    @pond = Pond.new
  end

  # GET /ponds/1/edit
  def edit
  end

  # POST /ponds
  # POST /ponds.json
  def create
    @pond = Pond.new(pond_params)

    respond_to do |format|
      if @pond.save
        format.html { redirect_to @pond, notice: 'Pond was successfully created.' }
        format.json { render :show, status: :created, location: @pond }
      else
        format.html { render :new }
        format.json { render json: @pond.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ponds/1
  # PATCH/PUT /ponds/1.json
  def update
    respond_to do |format|
      if @pond.update(pond_params)
        format.html { redirect_to @pond, notice: 'Pond was successfully updated.' }
        format.json { render :show, status: :ok, location: @pond }
      else
        format.html { render :edit }
        format.json { render json: @pond.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ponds/1
  # DELETE /ponds/1.json
  def destroy
    @pond.destroy
    respond_to do |format|
      format.html { redirect_to ponds_url, notice: 'Pond was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pond
      @pond = Pond.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pond_params
      #params[:pond]
      params.require(:pond).permit(:name, :water_type)
    end
end

app/controllers/tadpoles_controller.rb
class TadpolesController < ApplicationController
  before_action :set_tadpole, only: [:show, :edit, :update, :destroy]

  # GET /tadpoles
  # GET /tadpoles.json
  def index
    @tadpoles = Tadpole.all
  end

  # GET /tadpoles/1
  # GET /tadpoles/1.json
  def show
  end

  # GET /tadpoles/new
  def new
    @frog = Frog.find(params[:frog_id])
    @tadpole = Tadpole.new
  end

  # GET /tadpoles/1/edit
  def edit
  end

  # POST /tadpoles
  # POST /tadpoles.json
  def create
    @tadpole = Tadpole.new(tadpole_params)
    respond_to do |format|
      if @tadpole.save
        format.html { redirect_to @tadpole, notice: 'Tadpole was successfully created.' }
        format.json { render :show, status: :created, location: @tadpole }
      else
        format.html { render :new }
        format.json { render json: @tadpole.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tadpoles/1
  # PATCH/PUT /tadpoles/1.json
  def update
    respond_to do |format|
      if @tadpole.update(tadpole_params)
        format.html { redirect_to @tadpole, notice: 'Tadpole was successfully updated.' }
        format.json { render :show, status: :ok, location: @tadpole }
      else
        format.html { render :edit }
        format.json { render json: @tadpole.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tadpoles/1
  # DELETE /tadpoles/1.json
  def destroy
    @tadpole.destroy
    respond_to do |format|
      format.html { redirect_to tadpoles_url, notice: 'Tadpole was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def evolve
    @tadpole = Tadpole.find(params[:id])
    @parent_frog = Frog.find(@tadpole.frog_id)
    @frog = Frog.new(name: @tadpole.name, color: @tadpole.color, pond_id: @parent_frog.pond_id)
    if @frog.save
      @tadpole.destroy
      respond_to do |format|
        format.html { redirect_to frogs_url, notice: 'Tadpole was successfully evolved.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tadpole
      @tadpole = Tadpole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tadpole_params
      #params[:tadpole]
      params.require(:tadpole).permit(:name, :color, :frog_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frogs_helper.rb
module FrogsHelper
end

app/helpers/ponds_helper.rb
module PondsHelper
end

app/helpers/tadpoles_helper.rb
module TadpolesHelper
end

app/views/application/index.html.erb
<h1>Welcome to Pollywog Ranch</h1>
<p>Please select from the choices above.</p>

app/views/frogs/_form.html.erb
<%= form_for(@frog) do |f| %>
  <% if @frog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@frog.errors.count, "error") %> prohibited this frog from being saved:</h2>

      <ul>
      <% @frog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>

      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Name " %>
    <%= f.text_field :name %>

    <%= f.label :color, "Color " %>
    <%= f.text_field :color %>

    <%= f.label :lives, "Lives " %>
    <%= f.collection_select(:pond_id, Pond.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/frogs/edit.html.erb
<h1>Editing frog</h1>

<%= render 'form' %>

<%= link_to 'Show', @frog %> |
<%= link_to 'Back', frogs_path %>

app/views/frogs/index.html.erb
<h1>Frogs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @frogs.each do |frog| %>
      <tr>
        <td><%= link_to frog.name, frog %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Frog', new_frog_path %>

app/views/frogs/new.html.erb
<h1>New frog</h1>

<%= render 'form' %>

<%= link_to 'Back', frogs_path %>

app/views/frogs/show.html.erb
<h1><%= @frog.name %> Frog</h1>
<p>Color: <%= @frog.color %></p>
<p>Lives: <a href="/ponds/<%= @frog.pond.id %>"><%= @frog.pond.name %></a></p>
<% unless @frog.tadpoles.empty? %>
  <h2>Children</h2>
  <ol>
    <% @frog.tadpoles.each do |tadpole| %>
      <li><a href="/tadpoles/<%= tadpole.id %>"><%= tadpole.name %></a></li>
    <% end %>
  </ol><br>
<% end %>

<%= link_to 'Create new tadpole baby', new_frog_tadpole_path(@frog) %>
<br><br>
<%= link_to 'Back', frogs_path %> |
<%= link_to 'Edit', edit_frog_path(@frog) %> |
<%= link_to 'Delete', @frog, method: :delete, data: { confirm: 'Are you sure?' }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollywog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <a href="/ponds">Ponds</a> |
    <a href="/frogs">Frogs</a> |
    <a href="/tadpoles">Tadpoles</a>
  </nav>
  <p id="notice"><%= notice %></p>
  <%= yield %>

</body>
</html>

app/views/ponds/_form.html.erb
<%= form_for(@pond) do |f| %>
  <% if @pond.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pond.errors.count, "error") %> prohibited this pond from being saved:</h2>

      <ul>
      <% @pond.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">

    <%= f.label :name, "Name " %>
    <%= f.text_field :name %>

    <%= f.label :water_type, "Water type " %>
    <%= f.text_field :water_type %>

    <%= f.submit %>
  </div>
<% end %>

app/views/ponds/edit.html.erb
<h1>Editing pond</h1>

<%= render 'form' %>

<%= link_to 'Show', @pond %> |
<%= link_to 'Back', ponds_path %>

app/views/ponds/index.html.erb
<h1>Ponds</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ponds.each do |pond| %>
      <tr>
        <td><%= link_to pond.name , pond %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create a new pond', new_pond_path %>

app/views/ponds/new.html.erb
<h1>Create a new pond</h1>

<%= render 'form' %>

<%= link_to 'Back', ponds_path %>

app/views/ponds/show.html.erb
<h1><%= @pond.name %> Pond</h1>
<p>Water type: <%= @pond.water_type %></p>
<p>Resident frogs and their tadpoles:</p>

<ol>
  <% @pond.frogs.each do |frog| %>
    <li><%= link_to "#{frog.name} frog", frog_path(frog) %>
    <!-- <li><a href="/frogs/<%= frog.id %>"><%= frog.name %> frog</a> -->
      <ol>
        <% frog.tadpoles.each do |tadpole| %>
          <li><%= link_to "#{tadpole.name} tadpole", tadpole_path(tadpole) %>
          <!-- <li><a href="/tadpoles/<%= tadpole.id %>"><%= tadpole.name %> tadpole</a></li> -->
        <% end %>
      </ol>
    </li>
  <% end %>
</ol>

<%= link_to 'Back', ponds_path %> |
<%= link_to 'Edit', edit_pond_path(@pond) %> |
<%= link_to 'Destroy', @pond, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/tadpoles/_form.html.erb
<%= form_for(@tadpole) do |f| %>
  <% if @tadpole.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tadpole.errors.count, "error") %> prohibited this tadpole from being saved:</h2>

      <ul>
      <% @tadpole.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
    <%= f.hidden_field :color, :value => @frog.color %>
    <%= f.hidden_field :frog_id, :value => @frog.id %>

  <div class="actions">

    <%= f.submit %>
  </div>
<% end %>

app/views/tadpoles/edit.html.erb
<h1>Editing tadpole</h1>

<%= render 'form' %>

<%= link_to 'Show', @tadpole %> |
<%= link_to 'Back', tadpoles_path %>

app/views/tadpoles/index.html.erb
<h1>Tadpoles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tadpoles.each do |tadpole| %>
      <tr>
        <td><%= link_to tadpole.name, tadpole %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tadpoles/new.html.erb
<h1>Create a new tadpole for <%= @frog.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', tadpoles_path %>

app/views/tadpoles/show.html.erb
<h1><%= @tadpole.name %> Tadpole</h1>
<p>color: <%= @tadpole.color %></p>
<p>parent: <a href="/frogs/<%= @tadpole.frog.id %>"><%= @tadpole.frog.name %></a></p>
<p>lives: <a href="/ponds/<%= @tadpole.frog.pond.id %>"><%= @tadpole.frog.pond.name %></a></p>
<p><strong><%= link_to "Evolve into Frog", evolve_tadpoles_path %></strong></p>

<%= link_to 'Back', tadpoles_path %> |
<%= link_to 'Edit', edit_tadpole_path(@tadpole) %> |
<%= link_to 'Delete', @tadpole, method: :delete, data: {confirm: 'Are you sure?'} %>